spring:
  application:
    name: main
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    group-id: producer-group
    producer:
      topic: test-topic

server:
  port: 8080

secret:
  key: ${SECRET_KEY}

token:
  expire_time: ${TOKEN_EXPIRE_TIME}
  refresh_time: ${TOKEN_REFRESH_TIME}

cors:
  urls: "*"

camunda.bpm:
  admin-user:
    id: admin
    password: admin
  generic-properties:
    properties:
      historyTimeToLive: P1D

request-fee: 1
